requirements.txt
ride_with_me_backend/ride_with_me_backend/settings.py

- Added django-heroku package
- Added additional Heroku configuration to settings.py

Add Heroku configuration

---

README.md
rides/schema.py

- Added endpoint to retrieve all currently available rides
- Added README documentation for new endpoint

Create get available rides endpoint

---

rides/fixtures/ride_data.json
rides/schema.py

- Imported generic models for all data tables in GraphQL schema

Add all models to graphql schema

---

rides/tests/snapshots/snap_test_query.py
rides/tests/test_models.py

- Fixed all failing tests after updating fixtures

Fix failing tests

---

README.md

Adds more documentation to the searchRidesByCities query with examples of passing date arguments.

Update ReadMe for searchRidesByCities query

---

rides/schema.py
rides/tests/snapshots/snap_test_query.py
rides/tests/test_query.py

Here are the changes that should break any failing tests on master. I thought I pushed this up before I left yesterday but I must have forgotten to make a PR.

Fix and update failing tests on master

---

README.md
rides/schema.py
rides/tests/snapshots/snap_test_query.py
rides/tests/test_query.py

- Added, tested, and documented the GraphQL endpoint for retrieving a driver's pending requests

Create 'GET pending requests for driver' endpoint

---

README.md
ride_with_me_backend/urls.py
rides/schema.py
rides/tests/snapshots/snap_test_query.py
rides/tests/test_query.py

- Added, tested, and documented endpoint for updating the status of a ride. This can be used for both the 'cancel' and 'complete' ride functionality.

Create 'Update ride status' endpoint

---

.circleci/config.yml
.gitignore
Pipfile
Pipfile.lock
vars.ini

Added CircleCI configuration for automatic deployment to Heroku when merged to master

Add CircleCI build and deployment

---

README.md
rides/admin.py
rides/models.py
rides/schema.py

Create a Request

---

README.md
rides/schema.py
rides/tests/snapshots/snap_test_query.py
rides/tests/test_query.py

- Created and tested edit request endpoint
- Updated and standardized first 6 endpoints in README, still need to add documentation for edit request endpoint and standardize documentation for last two endpoints

Create Edit Request endpoint and update README

---

README.md
rides/schema.py

Delete ride passenger

---

rides/models.py
rides/schema.py

Example query to get all rides associated with user 2:
```graphql
query{
myRides(userId: 2){
id
description
driver{
id
firstName
lastName
}
ridepassengerSet{
passenger{
firstName
lastName
id
}
}
}
}
```
Response:
```graphql
{
"data": {
"myRides": [
{
"id": "2",
"description": "Three spots available in my van",
"driver": {
"id": "2",
"firstName": "Arnold",
"lastName": "Schwarzenegger"
},
"ridepassengerSet": [
{
"passenger": {
"firstName": "Natalie",
"lastName": "Portman",
"id": "7"
}
},
{
"passenger": {
"firstName": "Tom",
"lastName": "Hanks",
"id": "8"
}
},
{
"passenger": {
"firstName": "Jennifer",
"lastName": "Aniston",
"id": "9"
}
}
]
},
{
"id": "3",
"description": "Anyone need a ride this weekend?",
"driver": {
"id": "2",
"firstName": "Arnold",
"lastName": "Schwarzenegger"
}, …
```

My rides query

---

README.md
rides/schema.py

I created and documented the GraphQL endpoint for creating a RidePassenger. I based it off of the endpoint you created for deleting a RidePassenger since they have similar functions.

Create endpoint adding passenger to ride

---

README.md
rides/schema.py

Created and documented the endpoint for searching user by id. This endpoint can be used to display user information on the profile page.

Create find user by id endpoint

---

rides/schema.py

Per the wireframe, now Ride will have a custom field called "available_seats" which will show the number of available seats for that ride

Add available seats field when returning a ride

---

README.md
rides/schema.py

Returns two lists, one with startCities and one with endCities

Searchable Cities

---

README.md
rides/schema.py

- Tested, updated, and standardized all GraphQL endpoints in README
- Added uuid arguments to createRide, createRequest, deleteRidePassenger, myRides, and pendingRequests endpoints
Here is all the work I did this morning adding uuid requirements to the GraphQL endpoints that needed them. I also did an editing pass over the entire README, trying to clean up and standardize all the documentation.

Add uuid arguments to endpoints and standardize README

---

README.md

- Added variable notation for all GraphQL queries, not just the mutations

Add variable notation for all GraphQL queries

---

ride_with_me_backend/settings.py
rides/schema.py

-  Added SendGrid configuration
- Added email confirmation for denying requests, adding RidePassengers, and removing RidePassengers

Add email configuration and functionality
